// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wellness360.Data;

#nullable disable

namespace Wellness360.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240418011525_First")]
    partial class First
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Wellness360.Models.Vrapimi", b =>
                {
                    b.Property<string>("Numri")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<double>("Distanca")
                        .HasColumnType("float");

                    b.Property<int>("Kalorite")
                        .HasColumnType("int");

                    b.Property<int>("Koha")
                        .HasColumnType("int");

                    b.Property<double>("ShpejtesiaMesatare")
                        .HasColumnType("float");

                    b.HasKey("Numri");

                    b.ToTable("Vrapimi");
                });
#pragma warning restore 612, 618
        }
    }
}
