// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wellness360.Data;

#nullable disable

namespace Wellness360.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240806170230_6")]
    partial class _6
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Wellness360.Models.EmriUshqimit", b =>
                {
                    b.Property<string>("Ushqimi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Ushqimi");

                    b.ToTable("EmriUshqimits");
                });

            modelBuilder.Entity("Wellness360.Models.KategoriaEUshqimeve", b =>
                {
                    b.Property<string>("Kategoria")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Kategoria");

                    b.ToTable("KategoriaEUshqimeves");
                });

            modelBuilder.Entity("Wellness360.Models.RunningActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AverageSpeed")
                        .HasColumnType("float");

                    b.Property<double>("CaloriesBurned")
                        .HasColumnType("float");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("RunningActivities");
                });

            modelBuilder.Entity("Wellness360.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Wellness360.Models.Ushqimii", b =>
                {
                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Kategoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Ushqimi")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Data");

                    b.HasIndex("Kategoria");

                    b.HasIndex("Ushqimi");

                    b.ToTable("Ushqimiis");
                });

            modelBuilder.Entity("Wellness360.Models.Ushqimii", b =>
                {
                    b.HasOne("Wellness360.Models.KategoriaEUshqimeve", "KategoriaEUshqimeve")
                        .WithMany()
                        .HasForeignKey("Kategoria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Wellness360.Models.EmriUshqimit", "EmriUshqimit")
                        .WithMany()
                        .HasForeignKey("Ushqimi")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EmriUshqimit");

                    b.Navigation("KategoriaEUshqimeve");
                });
#pragma warning restore 612, 618
        }
    }
}
